"Applied fix from trunk for revision: 1714415  " ------------------------------------------------------------------------ r1714415 | jleroux | 2015-11-15 10:01:57 +0100 (dim. 15 nov. 2015) | 23 lignes
Fixes "Project Manager throws error if project user is not assigned to every project" OFBIZ-4206 reported by Tolulope Aganga-Williams and well commented by Mansour Al Akeel and Pierre Smits 

The project manager returns an error on the main page unless every user is added to every single project. It should return a list of just the projects the user is assigned to.

:ERROR MESSAGE: 
org.ofbiz.widget.screen.ScreenRenderException: Error rendering screen [component://common/widget/CommonScreens.xml#GlobalDecorator]: java.lang.IllegalArgumentException: Error running Groovy script at location [component://projectmgr/webapp/projectmgr/WEB-INF/actions/ListCurrentProjects.groovy]: org.ofbiz.service.ServiceAuthException: You have no access to the project#: 10040 (Error running Groovy script at location [component://projectmgr/webapp/projectmgr/WEB-INF/actions/ListCurrentProjects.groovy]: org.ofbiz.service.ServiceAuthException: You have no access to the project#: 10040) 
It defeats the point.

Mansour:
Pierre,
The patch seems to restrict access to this scree to "PROJECTMGR_ADMIN".
I am not sure if this issue is to be resolved in the screen or making the service returns projects the user has access to.
I appreciate your help here.

Pierre:
Hi Mansour,
You are right. The patch indeed does that and returns a blank screen for
users other than with access 'PROJECTMGR_ADMIN. Other users can look at
projects which will show projects the user is a member of.

jleroux:
I did not test all, but because of ListCurrentProjects.groovy, it seems to me that this is a better solution
I added the CommonAsk label to help lambda users better understand the situation (by asking :p)
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release14.12@1714416 13f79535-47bb-0310-9956-ffa450edef68