"Applied fix from trunk for revision: 1742018" ------------------------------------------------------------------------ r1742018 | jleroux | 2016-05-02 20:12:08 +0200 (lun. 02 mai 2016) | 3 lignes
Fixes an issue found by chance. This was changed from bsh to groovy by r1613432 but does not work. I tried many variants but none works, all return 
groovy.lang.MissingPropertyException: No such property: payment for class: script....
So back to origin :/
------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release15.12@1742019 13f79535-47bb-0310-9956-ffa450edef68