Applied bug fix from commit r1170473. This patch was applied on release 11.04 and it looks like that this bug does exists on 10.04 as well. PATCH: Exception when entering wrong current password on requirePasswordChange (https://issues.apache.org/jira/browse/OFBIZ-4356). A patch from Dimitri Unruh to fix the wrong current password on a required password change.
Orig Msg:
Here is a step-by-step how the error occures:
1) Request a new password by entering your userlogin
2) Login and you will get to the "requirePasswordChange"-Page (depending on properties)
3) If you enter a wrong current password on this page the exception is thrown.
OFBiz tries to call the service "updatePassword" with a bad userLogin and an Exception is thrown:

org.ofbiz.service.ServiceAuthException: User authorization is required for this service: updatePassword [updatePassword::file:/C:/Workspace/apache_ofbiz/framework/common/servicedef/services.xml::Update a UserLogin ...


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release10.04@1442185 13f79535-47bb-0310-9956-ffa450edef68