Applied fix from trunk for revision: 1035084 ===
Someone working in different timezone(for ex: PST or any other) should receive following error message while deleting record on EditProductFeatures page(https://localhost:8443/catalog/control/EditProductFeatures?productId=GZ-1006). This patch will fix the issue, Thanks Scott for the tip!

2010-11-15 03:53:00,577 (http-0.0.0.0-8443-2) [     ControlServlet.java:147:INFO ] [[[RemoveFeatureFromProduct] Request Begun, encoding=[UTF-8]- total:0.0,since last(Begin):0.0]]
2010-11-15 03:53:00,648 (http-0.0.0.0-8443-2) [    ConfigXMLReader.java:120:INFO ] controller loaded: 0.02s, 468 requests, 145 views in jndi:/0.0.0.0/catalog/WEB-INF/controller.xml
2010-11-15 03:53:00,662 (http-0.0.0.0-8443-2) [    ConfigXMLReader.java:120:INFO ] controller loaded: 0.0010s, 29 requests, 17 views in file:/home/ashish/ofbiz_dev/testing/framework/common/webcommon/WEB-INF/common-controller.xml
2010-11-15 03:53:00,668 (http-0.0.0.0-8443-2) [    ConfigXMLReader.java:120:INFO ] controller loaded: 0.0010s, 26 requests, 10 views in file:/home/ashish/ofbiz_dev/testing/framework/common/webcommon/WEB-INF/portal-controller.xml
2010-11-15 03:53:00,672 (http-0.0.0.0-8443-2) [    ConfigXMLReader.java:120:INFO ] controller loaded: 0.0s, 2 requests, 0 views in file:/home/ashish/ofbiz_dev/testing/applications/commonext/webapp/WEB-INF/controller.xml
2010-11-15 03:53:00,932 (http-0.0.0.0-8443-2) [        RemoveValue.java:62 :WARN ] In remove-value a value was not found with the specified valueAcsr: productFeatureAppl, not removing
2010-11-15 03:53:00,939 (http-0.0.0.0-8443-2) [    TransactionUtil.java:370:WARN ] 
---- exception report ----------------------------------------------------------
[TransactionUtil.setRollbackOnly] Calling transaction setRollbackOnly; this stack trace shows where this is happening:
Exception: java.lang.Exception
Message: Error in simple-method [Remove Feature from Product [file:/home/ashish/ofbiz_dev/testing/applications/product/script/org/ofbiz/product/feature/ProductFeatureServices.xml#removeFeatureFromProduct]]: In remove-value a value was not found with the specified valueAcsr: productFeatureAppl, not removing
---- stack trace ---------------------------------------------------------------
java.lang.Exception: Error in simple-method [Remove Feature from Product [file:/home/ashish/ofbiz_dev/testing/applications/product/script/org/ofbiz/product/feature/ProductFeatureServices.xml#removeFeatureFromProduct]]: In remove-value a value was not found with the specified valueAcsr: productFeatureAppl, not removing
org.ofbiz.entity.transaction.TransactionUtil.setRollbackOnly(TransactionUtil.java:370)
org.ofbiz.entity.transaction.TransactionUtil.rollback(TransactionUtil.java:312)
org.ofbiz.minilang.SimpleMethod.exec(SimpleMethod.java:870)
org.ofbiz.minilang.SimpleMethod.runSimpleMethod(SimpleMethod.java:160)
org.ofbiz.minilang.SimpleMethod.runSimpleService(SimpleMethod.java:142)
org.ofbiz.minilang.SimpleServiceEngine.serviceInvoker(SimpleServiceEngine.java:78)
org.ofbiz.minilang.SimpleServiceEngine.runSync(SimpleServiceEngine.java:53)
org.ofbiz.service.ModelServiceReader$GenericInvokerImpl.runSync(ModelServiceReader.java:761)
_$gen.file_58$.home.ashish.ofbiz_95$dev.testing.applications.product.servicedef.services_95$feature_46$xml_35$removeFeatureFromProduct.runSync(file:/home/ashish/ofbiz_dev/testing/applications/product/servicedef/services_feature.xml#removeFeatureFromProduct:99)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:399)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:226)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:165)
org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:336)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:633)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:379)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:230)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:93)
javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:329)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-11-15 03:53:00,940 (http-0.0.0.0-8443-2) [  ServiceDispatcher.java:543:ERROR] Error in Service [removeFeatureFromProduct]: In remove-value a value was not found with the specified valueAcsr: productFeatureAppl, not removing
2010-11-15 03:53:00,955 (http-0.0.0.0-8443-2) [    TransactionUtil.java:334:ERROR] 
---- exception report ----------------------------------------------------------
[TransactionUtil.rollback]
Exception: java.lang.Exception
Message: Stack Trace
---- stack trace ---------------------------------------------------------------
java.lang.Exception: Stack Trace
org.ofbiz.entity.transaction.TransactionUtil.rollback(TransactionUtil.java:333)
org.ofbiz.entity.transaction.TransactionUtil.rollback(TransactionUtil.java:310)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:547)
org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:226)
org.ofbiz.service.GenericDispatcher.runSync(GenericDispatcher.java:165)
org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:336)
org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:633)
org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:379)
org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:230)
org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:93)
javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:329)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:555)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
java.lang.Thread.run(Thread.java:619)
--------------------------------------------------------------------------------

2010-11-15 03:53:00,956 (http-0.0.0.0-8443-2) [    TransactionUtil.java:344:INFO ] [TransactionUtil.rollback] transaction rolled back
2010-11-15 03:53:00,956 (http-0.0.0.0-8443-2) [  ServiceDispatcher.java:599:INFO ] Sync service [catalog/removeFeatureFromProduct] finished in [263] milliseconds
2010-11-15 03:53:00,957 (http-0.0.0.0-8443-2) [     RequestHandler.java:634:INFO ] Ran Event [service:#removeFeatureFromProduct] from [request], result is [error]
2010-11-15 03:53:00,958 (http-0.0.0.0-8443-2) [     RequestHandler.java:417:ERROR] Request RemoveFeatureFromProduct caused an error with the following message: In remove-value a value was not found with the specified valueAcsr: productFeatureAppl, not removing
2010-11-15 03:53:00,958 (http-0.0.0.0-8443-2) [     RequestHandler.java:737:INFO ] Rendering View [EditProductFeatures], sessionId=1F2B0DAF1681C9B9C243C57DEE6A8FB1.jvm1
2010-11-15 03:53:01,068 (http-0.0.0.0-8443-2) [      ScreenFactory.java:130:INFO ] Got 41 screens in 0.02s from: file:/home/ashish/ofbiz_dev/testing/applications/product/widget/catalog/ProductScreens.xml



git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release10.04@1035085 13f79535-47bb-0310-9956-ffa450edef68