"Applied fix from trunk for revision: 1304200  " ------------------------------------------------------------------------ r1304200 | jleroux | 2012-03-23 07:26:22 +0100 (ven., 23 mars 2012) | 15 lines
A patch from Kiran Gawde  "StringIndexOutOfBoundsException in OfbizContentTransform" https://issues.apache.org/jira/browse/OFBIZ-4464

Fixes this bug:
---- exception report ----------------------------------------------------------
Error in request handler:
Exception: org.ofbiz.widget.screen.ScreenRenderException
Message: Error rendering screen component://ecommerce/widget/CommonScreens.xml#main-decorator: java.lang.StringIndexOutOfBoundsException: String index out of range: 0 (String index out of range: 0)
---- cause ---------------------------------------------------------------------
Exception: java.lang.StringIndexOutOfBoundsException
Message: String index out of range: 0
---- stack trace ---------------------------------------------------------------
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
java.lang.String.charAt(String.java:686)
org.ofbiz.webapp.ftl.OfbizContentTransform$1.close(OfbizContentTransform.java:97)

------------------------------------------------------------------------
?\026

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release10.04@1304201 13f79535-47bb-0310-9956-ffa450edef68