"Applied fix from trunk for revision: 1721067" ------------------------------------------------------------------------ r1721067 | jleroux | 2015-12-20 22:14:05 +0100 (dim. 20 déc. 2015) | 6 lignes
Prevents a possible "NPE", found in trunk demo logs (it's a treasure I will continue to dig in...)

freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> lastContent.description  [in template "component://ecommerce/webapp/ecommerce/content/viewcontent.ftl" at line 38, column 38]


------------------------------------------------------------------------


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/branches/release14.12@1721068 13f79535-47bb-0310-9956-ffa450edef68